[package]
name = "resync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.6"
git2 = "0.13"
nom = "7"
nom_locate = "4.0.0"
